builds:
  - env:
    - CGO_ENABLED=0
    main: main.go
    ldflags: '-s -w -X github.com/sensu-community/sensu-plugin-sdk/version.build={{.Version}} -X github.com/sensu-community/sensu-plugin-sdk/version.commit={{.Commit}} -X github.com/sensu-community/sensu-plugin-sdk/version.date={{.Date}}'
    # Set the binary output location to bin/ so archive will comply with Sensu Go Asset structure
    binary: bin/{{ .ProjectName }}
    goos:
      - linux
      - windows
    goarch:
      - amd64
      - arm64
    targets:
      - linux_amd64
      - linux_arm64
      - windows_amd64

checksum:
  name_template: "{{ .ProjectName }}_{{ .Version }}_sha512-checksums.txt"
  algorithm: sha512

archives:
  - id: tar
    format: tar.gz
    files:
      - LICENSE
      - README.md
      - CHANGELOG.md
